Adicionar Vinicio em Membros
polichain/jekyll-website pull request #41
Opened 2024-06-14 19:23 UTC by vinicio-mendes

Atualizei a página de membros com o link para a pagina Vinicio Mendes Roberto e adicionei mais informações sobre mim.

2024-06-17 18:30 UTC, otaviootavio requested changes
remova as mudanças do Gemfile.lock

2024-06-19 11:49 UTC, vinicio-mendes commented
Removendo alteracoes do Gemfile.lock x2

2024-06-19 12:43 UTC, otaviootavio approved these changes

2024-06-19 12:43 UTC, otaviootavio commented on Gemfile.lock
> +    sass-embedded
Adicione `sass-embedded (1.62.1)`

2024-06-19 12:43 UTC, merged